# Individual C Programs Execution Make File

# NOTE: To be able to run the following make commands, your cwd needs to be CPRGS dir

#Speciy the name of your program here	
ProgramName = CDM1

# commands:
compileAndLink:
	gcc $(ProgramName).c -o outputs/$(ProgramName).exe

run:
	.\outputs/$(ProgramName)

genppf:
	gcc -E $(ProgramName).c -o outputs/$(ProgramName).i

genasm: genppf
	gcc -S outputs/$(ProgramName).i -o outputs/$(ProgramName).s

genulobj: genasm
	gcc -C outputs/$(ProgramName).s -o outputs/$(ProgramName).o

clean:
	del /Q outputs\$(ProgramName).*